--Start Create Tables-------------------------------------
create table _prtk (notificationNumber text,protocolNumber text,versionNumber integer,place text,protocolDate text,signDate text,publishDate text,href text,foundationProtocolNumber text,parentProtocolNumber text,uid SERIAL PRIMARY KEY,file_id integer references files_list(id) on delete cascade);
create table _prtk_commission (regNumber text,name text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk(uid) on delete cascade);
create table _prtk_commission_protComMems (uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_commission(uid) on delete cascade );
create table _prtk_commission_protComMems_protComMem (id integer,name text,present text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_commission_protComMems(uid) on delete cascade );
create table _prtk_commission_protComMems_protComMem_role (roleId integer,name text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_commission_protComMems_protComMem(uid) on delete cascade );
create table _prtk_documentMetas (uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk(uid) on delete cascade );
create table _prtk_documentMetas_documentMeta (sid text,fileName text,docDescription text,url text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_documentMetas(uid) on delete cascade );
create table _prtk_documentMetas_documentMeta_cryptoSigns (signature text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_documentMetas_documentMeta(uid) on delete cascade );
create table _prtk_modification (initiativeType text,modificationDate text,info text,authorityName text,desNumber text,authorityType text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk(uid) on delete cascade );
create table _prtk_printForm (fileName text,url text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk(uid) on delete cascade );
create table _prtk_printForm_cryptoSigns (signature text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_printForm(uid) on delete cascade );
create table _prtk_protLots (uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk(uid) on delete cascade );
create table _prtk_protLots_protLot (lotNumber text,allAbsent text,contractMulti text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots(uid) on delete cascade );
create table _prtk_protLots_protLot_apps (uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot(uid) on delete cascade );
create table _prtk_protLots_protLot_apps_app (journalNumber text,appDate text,admitted text,commonInfo text,participantPresent text,appRating text,appFormat text,price numeric,goodsDelivered text,expensesInfo text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot_apps(uid) on delete cascade );
create table _prtk_protLots_protLot_apps_app_admRess (uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot_apps_app(uid) on delete cascade );
create table _prtk_protLots_protLot_apps_app_admRess_admRes (admitted text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot_apps_app_admRess(uid) on delete cascade );
create table _prtk_protLots_protLot_apps_app_admRess_admRes_appRejReas (explanation text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot_apps_app_admRess_admRes(uid) on delete cascade );
create table _prtk_protLots_protLot_apps_app_admRess_admRes_appRejReas_nsiRejectReas (id integer,reason text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot_apps_app_admRess_admRes_appRejReas(uid) on delete cascade );
create table _prtk_protLots_protLot_apps_app_admRess_admRes_protComMem (id integer,name text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot_apps_app_admRess_admRes(uid) on delete cascade );
create table _prtk_protLots_protLot_apps_app_admRess_admRes_protComMem_role (roleid bigint,name text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot_apps_app_admRess_admRes_protComMem(uid) on delete cascade );
create table _prtk_protLots_protLot_apps_app_admRess_appRejReas (explanation text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot_apps_app_admRess(uid) on delete cascade );
create table _prtk_protLots_protLot_apps_app_admRess_appRejReas_nsiRejectReas (id integer,reason text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot_apps_app_admRess_appRejReas(uid) on delete cascade );
create table _prtk_protLots_protLot_apps_app_appParts (uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot_apps_app(uid) on delete cascade );
create table _prtk_protLots_protLot_apps_app_appParts_appPart (participantType text,inn bigint,kpp integer,idNumber text,idNumberExtension text,organizationName text,factualAddress text,postAddress text,additionalInfo text,organizationForm text,contactEMail text,contactPhone text,contactFax text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot_apps_app_appParts(uid) on delete cascade );
create table _prtk_protLots_protLot_apps_app_appParts_appPart_contactInfo (lastName text,firstName text,middleName text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot_apps_app_appParts_appPart(uid) on delete cascade );
create table _prtk_protLots_protLot_apps_app_appParts_appPart_country (countryCode integer,countryFullName text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot_apps_app_appParts_appPart(uid) on delete cascade );
create table _prtk_protLots_protLot_apps_app_contrConds (uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot_apps_app(uid) on delete cascade );
create table _prtk_protLots_protLot_apps_app_contrConds_contrCond (condValue text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot_apps_app_contrConds(uid) on delete cascade );
create table _prtk_protLots_protLot_apps_app_contrConds_contrCond_crit (id integer,criterionType text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot_apps_app_contrConds_contrCond(uid) on delete cascade );
create table _prtk_protLots_protLot_apps_app_lastPrice (price numeric,date text,increaseInitialPrice text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot_apps_app(uid) on delete cascade );
create table _prtk_protLots_protLot_apps_app_reqComps (uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot_apps_app(uid) on delete cascade );
create table _prtk_protLots_protLot_apps_app_reqComps_reqComp (ordinalNumber text,availabilityType text,reason text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot_apps_app_reqComps(uid) on delete cascade );
create table _prtk_protLots_protLot_criterias (NIR text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot(uid) on delete cascade );
create table _prtk_protLots_protLot_criterias_manual (criterionValue text,evalValue text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot_criterias(uid) on delete cascade );
create table _prtk_protLots_protLot_criterias_manual_childrenCriteria (id integer,name text,criterionValue text,evalValue text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot_criterias_manual(uid) on delete cascade );
create table _prtk_protLots_protLot_criterias_manual_nsiEvalCriterion (id integer,name text,"order" text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot_criterias_manual(uid) on delete cascade );
create table _prtk_protLots_protLot_documentReqs (uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot(uid) on delete cascade );
create table _prtk_protLots_protLot_documentReqs_documentReq (sid text,ordinalNumber text,reqValue text,uid SERIAL PRIMARY KEY, parent_uid bigint references _prtk_protLots_protLot_documentReqs(uid) on delete cascade );
--End Create Tables---------------------------------------
